
name: Tests
'on':
  push:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  schedule:
    - cron: '0 6 * * 0'

jobs:
  test:
    name: 'Node.js v${{ matrix.node }}'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - 14
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '${{ matrix.node }}'
        env:
          BASE_URL: ${{ secrets.SECRET1 }}
          KEY : ${{ secrets.SECRET2 }}
      - uses: actions/checkout@v2
      - name: 'Cache node_modules'
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-v${{ matrix.node }}-${{ hashFiles('**/package.json') }}
          restore-keys: |

            ${{ runner.os }}-node-v${{ matrix.node }}-
      - name: Install Dependencies
        run: | 
          npm install mocha
          npm install axios
          npm install dotenv
          npm install chai
          npm install mochawesome
          touch .env
          echo BASE_URL="${{ secrets.SECRET1 }}" >> .env
          echo KEY="${{ secrets.SECRET2 }}" >> .env
      - name: Run All Node.js Tests
        run: npm run test-mocha